services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: fifa
    volumes:
      - ./db/fifa_male_players.sql:/docker-entrypoint-initdb.d/fifa_male_players.sql
    ports:
      - '3306:3306'

  # backend:
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mysql
  # frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend